"""elimine la columna direccion

Revision ID: 0b918802abbe
Revises: aef0dccb5426
Create Date: 2023-07-26 22:44:28.746670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b918802abbe'
down_revision = 'aef0dccb5426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
