"""creacion de la tabla mascotas

Revision ID: 2e0128467afb
Revises: 0b918802abbe
Create Date: 2023-07-27 19:24:31.948232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0128467afb'
down_revision = '0b918802abbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('Perro', 'Gato', 'Cuy', name='tipomascota'), nullable=False),
    sa.Column('sexo', sa.Enum('Macho', 'Hembra', 'Helicoptero', 'Otro', name='sexomascota'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    # ### end Alembic commands ###
